name: Build Rucio JupyterLab Extension Tarball

on:
  push:
    branches: [ main ]
    paths:
      - 'rucio-jlab-deps/**'

jobs:
  build-tarball:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc zlib1g-dev libbz2-dev libreadline-dev \
          libsqlite3-dev libssl-dev tk-dev libffi-dev liblzma-dev uuid-dev \
          libgdbm-dev libnsl-dev git curl

    - name: Install Python 3.11.8 via pyenv and run build
      run: |
        # Install pyenv
        curl https://pyenv.run | bash

        # Set up pyenv environment
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"

        # Install and use Python 3.11.8
        pyenv install 3.11.8
        pyenv global 3.11.8

        # Confirm Python version
        python --version

        # Make build script executable and run it
        chmod +x rucio-jlab-deps/make_tarball.sh
        ./rucio-jlab-deps/make_tarball.sh

    - name: Upload tarball artifact
      uses: actions/upload-artifact@v4
      with:
        name: rucio-jlab-deps
        path: rucio-jlab-deps-*.tar.gz
